import{a as w,S as P,i as q}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function h(o,t){const c="https://pixabay.com",a="/api/",e="?key=42408826-646f1c33dda85bc33c99aac2a",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,s=c+a+e+r;return(await w.get(s)).data}const u=document.querySelector(".gallery");function p(o){const t=o.hits.map(({webformatURL:a,largeImageURL:e,tags:r,likes:s,views:f,comments:S,downloads:v})=>`<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-img" src="${a}" alt="${r}" />
  <div class="image-description">
    <p><b>Likes: </b>${s}</p>
    <p><b>Views: </b>${f}</p>
    <p><b>Comments: </b>${S}</p>
    <p><b>Downloads: </b>${v}</p>
  </div>
  </a>
</li>`).join("");u.insertAdjacentHTML("beforeend",t),new P(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const $=document.querySelector(".img-search-form"),g=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");let l,n,y;$.addEventListener("submit",M);m.addEventListener("click",O);async function M(o){if(o.preventDefault(),b(),u.innerHTML="",l=o.target.elements.query.value.trim(),n=1,l===""){i("Sorry, there are no search terms entered. Please try again!");return}L();try{const t=await h(l,n);if(y=Math.ceil(t.totalHits/15),t.totalHits===0){d(),i("Sorry, there are no images matching your search query. Please try again!");return}p(t)}catch(t){i(t)}d(),E(),o.target.reset()}async function O(){n+=1,L();try{const t=await h(l,n);p(t)}catch(t){i(t)}d(),E();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function x(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function L(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function i(o){q.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function E(){n>=y?(b(),i("We're sorry, but you've reached the end of search results.")):x()}
//# sourceMappingURL=commonHelpers.js.map
